name: Arcaflow CI Workflow
on:
  push:
    branches:
      - "**"
  release:
    types:
      - published
jobs:
  act:
    uses: jdowni000/arcaflow-container-toolkit/.github/workflows/reusable_workflow.yaml@test
    with:
      image_name: ${{ github.event.repository.name }}
      image_tag: 'latest'
      multi_arch: true
    secrets:
      QUAY_NAMESPACE: ${{ secrets.QUAY_NAMESPACE }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  docsgen:
    needs: act
    uses: arcalot/arcaflow-docsgen/.github/workflows/reusable_workflow.yaml@main
    permissions:
      contents: write
      pull-requests: write
    with:
      plugin_path: "arcaflow_plugin_uperf/uperf_plugin.py"
